name: Jonathan Crane
description: Software Development Engineer at Amazon | 2+ Years Experience
email: jonathan.avi.crane@gmail.com
github_username: jcrane613
linkedin_username: jonathan-crane-786226198
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
baseurl: ""
url: "https://jcrane613.github.io"
